eureka:
  client:
    service-url:
      defaultZone: http://b-eureka-service01:7003/eureka/,http://b-eureka-service02:7003/eureka/,http://b-eureka-service03:7003/eureka/

spring:
  zipkin:
     base-url: http://10.10.8.101:7006
     #enabled: false
     compression:
       enabled: true
     #service.name: sleuth-service
     locator:
       discovery:
         enabled: true
logging:
  level: debug
