eureka:
  client:
    service-url:
      defaultZone: http://b-eureka-service01:8080/eureka/,http://b-eureka-service02:8080/eureka/,http://b-eureka-service03:8080/eureka/

spring:
  zipkin:
     base-url: http://b-sleuth-service:7004
     #enabled: false
     compression:
       enabled: true
     #service.name: sleuth-service
     locator:
       discovery:
         enabled: true
logging:
  level: debug
