eureka:
  client:
    service-url:
      defaultZone: http://b-eureka-service01:7002/eureka/,http://b-eureka-service02:7003/eureka/,http://b-eureka-service03:7004/eureka/

spring:
  zipkin:
    base-url: http://b-sleuth-service:7005
     #enabled: false
    compression:
      enabled: true
     #service.name: sleuth-service
    locator:
      discovery:
        enabled: true
  jackson:
    serialization:
      indent_output: true

endpoints:
  health:
    sensitive: false
    enabled: true
  actuator:
    enabled: true
    sensitive: false
  beans:
    sensitive: false
    enabled: true


management:
  security:
    enabled: false

logging:
  level: debug



