eureka:
  client:
    service-url:
      defaultZone: http://b-eureka-service01:7002/eureka/,http://b-eureka-service02:7003/eureka/,http://b-eureka-service03:7004/eureka/

spring:
  zipkin:
    base-url: http://b-sleuth-service:7005
     #enabled: false
    compression:
      enabled: true
     #service.name: sleuth-service
    locator:
      discovery:
        enabled: true
  boot:
    admin:
      url: http://b-cloud-admin-service:7006
logging:
  level: debug

info:
  version: @project.version@

