server:
  port: 7104

jwt:
  valid:
    time: 72000 #72000 jwt 的有效时间

spring:
  redis:
    database: 0
    host: redis
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 3
      min-idle: 1
    timeout: 0
    