server:
  port: 8101
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.10.8.101:3306/taichi
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
      max-active: 20
      max-idle: 50
      min-idle: 5
      initial-size: 10

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.blife.sys.model

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql